/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsTopicIndexRouteImport } from './routes/news.$topic.index'
import { Route as NewsTopicCategoryRouteImport } from './routes/news.$topic.$category'
import { Route as NewsArticleIdRouteImport } from './routes/news.article.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsTopicIndexRoute = NewsTopicIndexRouteImport.update({
  id: '/$topic/',
  path: '/$topic/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsTopicCategoryRoute = NewsTopicCategoryRouteImport.update({
  id: '/$topic/$category',
  path: '/$topic/$category',
  getParentRoute: () => NewsRoute,
} as any)
const NewsArticleIdRoute = NewsArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRouteWithChildren
  '/portal': typeof PortalRoute
  '/news/': typeof NewsIndexRoute
  '/news/$topic/$category': typeof NewsTopicCategoryRoute
  '/news/article/$id': typeof NewsArticleIdRoute
  '/news/$topic/': typeof NewsTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRoute
  '/news': typeof NewsIndexRoute
  '/news/$topic/$category': typeof NewsTopicCategoryRoute
  '/news/article/$id': typeof NewsArticleIdRoute
  '/news/$topic': typeof NewsTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news': typeof NewsRouteWithChildren
  '/portal': typeof PortalRoute
  '/news/': typeof NewsIndexRoute
  '/news/$topic/$category': typeof NewsTopicCategoryRoute
  '/news/article/$id': typeof NewsArticleIdRoute
  '/news/$topic/': typeof NewsTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/news'
    | '/portal'
    | '/news/'
    | '/news/$topic/$category'
    | '/news/article/$id'
    | '/news/$topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/news'
    | '/news/$topic/$category'
    | '/news/article/$id'
    | '/news/$topic'
  id:
    | '__root__'
    | '/'
    | '/news'
    | '/portal'
    | '/news/'
    | '/news/$topic/$category'
    | '/news/article/$id'
    | '/news/$topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRouteWithChildren
  PortalRoute: typeof PortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$topic/': {
      id: '/news/$topic/'
      path: '/$topic'
      fullPath: '/news/$topic/'
      preLoaderRoute: typeof NewsTopicIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$topic/$category': {
      id: '/news/$topic/$category'
      path: '/$topic/$category'
      fullPath: '/news/$topic/$category'
      preLoaderRoute: typeof NewsTopicCategoryRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/article/$id': {
      id: '/news/article/$id'
      path: '/article/$id'
      fullPath: '/news/article/$id'
      preLoaderRoute: typeof NewsArticleIdRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface NewsRouteChildren {
  NewsIndexRoute: typeof NewsIndexRoute
  NewsTopicCategoryRoute: typeof NewsTopicCategoryRoute
  NewsArticleIdRoute: typeof NewsArticleIdRoute
  NewsTopicIndexRoute: typeof NewsTopicIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIndexRoute: NewsIndexRoute,
  NewsTopicCategoryRoute: NewsTopicCategoryRoute,
  NewsArticleIdRoute: NewsArticleIdRoute,
  NewsTopicIndexRoute: NewsTopicIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRouteWithChildren,
  PortalRoute: PortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
