/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDangKyRouteImport } from './routes/admin.dang-ky'
import { Route as AdminHoiPhiRouteImport } from './routes/admin.hoi-phi'
import { Route as AdminHoiVienRouteImport } from './routes/admin.hoi-vien'
import { Route as AdminNguoiDungRouteImport } from './routes/admin.nguoi-dung'
import { Route as AdminPhanBienRouteImport } from './routes/admin.phan-bien'
import { Route as AdminQuangCaoRouteImport } from './routes/admin.quang-cao'
import { Route as AdminTaiNguyenRouteImport } from './routes/admin.tai-nguyen'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsDaLuuRouteImport } from './routes/news.da-luu'
import { Route as NewsTimKiemRouteImport } from './routes/news.tim-kiem'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalDangKyRouteImport } from './routes/portal/dang-ky'
import { Route as AdminBaiVietIndexRouteImport } from './routes/admin.bai-viet.index'
import { Route as AdminBaiVietIdRouteImport } from './routes/admin.bai-viet.$id'
import { Route as NewsTopicIndexRouteImport } from './routes/news.$topic.index'
import { Route as NewsTopicCategoryRouteImport } from './routes/news.$topic.$category'
import { Route as NewsArticleIdRouteImport } from './routes/news.article.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDangKyRoute = AdminDangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoiPhiRoute = AdminHoiPhiRouteImport.update({
  id: '/hoi-phi',
  path: '/hoi-phi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoiVienRoute = AdminHoiVienRouteImport.update({
  id: '/hoi-vien',
  path: '/hoi-vien',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNguoiDungRoute = AdminNguoiDungRouteImport.update({
  id: '/nguoi-dung',
  path: '/nguoi-dung',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhanBienRoute = AdminPhanBienRouteImport.update({
  id: '/phan-bien',
  path: '/phan-bien',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuangCaoRoute = AdminQuangCaoRouteImport.update({
  id: '/quang-cao',
  path: '/quang-cao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaiNguyenRoute = AdminTaiNguyenRouteImport.update({
  id: '/tai-nguyen',
  path: '/tai-nguyen',
  getParentRoute: () => AdminRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsDaLuuRoute = NewsDaLuuRouteImport.update({
  id: '/da-luu',
  path: '/da-luu',
  getParentRoute: () => NewsRoute,
} as any)
const NewsTimKiemRoute = NewsTimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => NewsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDangKyRoute = PortalDangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => PortalRoute,
} as any)
const AdminBaiVietIndexRoute = AdminBaiVietIndexRouteImport.update({
  id: '/bai-viet/',
  path: '/bai-viet/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBaiVietIdRoute = AdminBaiVietIdRouteImport.update({
  id: '/bai-viet/$id',
  path: '/bai-viet/$id',
  getParentRoute: () => AdminRoute,
} as any)
const NewsTopicIndexRoute = NewsTopicIndexRouteImport.update({
  id: '/$topic/',
  path: '/$topic/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsTopicCategoryRoute = NewsTopicCategoryRouteImport.update({
  id: '/$topic/$category',
  path: '/$topic/$category',
  getParentRoute: () => NewsRoute,
} as any)
const NewsArticleIdRoute = NewsArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dang-nhap': typeof DangNhapRoute
  '/news': typeof NewsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/admin/dang-ky': typeof AdminDangKyRoute
  '/admin/hoi-phi': typeof AdminHoiPhiRoute
  '/admin/hoi-vien': typeof AdminHoiVienRoute
  '/admin/nguoi-dung': typeof AdminNguoiDungRoute
  '/admin/phan-bien': typeof AdminPhanBienRoute
  '/admin/quang-cao': typeof AdminQuangCaoRoute
  '/admin/tai-nguyen': typeof AdminTaiNguyenRoute
  '/news/da-luu': typeof NewsDaLuuRoute
  '/news/tim-kiem': typeof NewsTimKiemRoute
  '/portal/dang-ky': typeof PortalDangKyRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/bai-viet/$id': typeof AdminBaiVietIdRoute
  '/news/$topic/$category': typeof NewsTopicCategoryRoute
  '/news/article/$id': typeof NewsArticleIdRoute
  '/admin/bai-viet/': typeof AdminBaiVietIndexRoute
  '/news/$topic/': typeof NewsTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dang-nhap': typeof DangNhapRoute
  '/admin/dang-ky': typeof AdminDangKyRoute
  '/admin/hoi-phi': typeof AdminHoiPhiRoute
  '/admin/hoi-vien': typeof AdminHoiVienRoute
  '/admin/nguoi-dung': typeof AdminNguoiDungRoute
  '/admin/phan-bien': typeof AdminPhanBienRoute
  '/admin/quang-cao': typeof AdminQuangCaoRoute
  '/admin/tai-nguyen': typeof AdminTaiNguyenRoute
  '/news/da-luu': typeof NewsDaLuuRoute
  '/news/tim-kiem': typeof NewsTimKiemRoute
  '/portal/dang-ky': typeof PortalDangKyRoute
  '/admin': typeof AdminIndexRoute
  '/news': typeof NewsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/bai-viet/$id': typeof AdminBaiVietIdRoute
  '/news/$topic/$category': typeof NewsTopicCategoryRoute
  '/news/article/$id': typeof NewsArticleIdRoute
  '/admin/bai-viet': typeof AdminBaiVietIndexRoute
  '/news/$topic': typeof NewsTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dang-nhap': typeof DangNhapRoute
  '/news': typeof NewsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/admin/dang-ky': typeof AdminDangKyRoute
  '/admin/hoi-phi': typeof AdminHoiPhiRoute
  '/admin/hoi-vien': typeof AdminHoiVienRoute
  '/admin/nguoi-dung': typeof AdminNguoiDungRoute
  '/admin/phan-bien': typeof AdminPhanBienRoute
  '/admin/quang-cao': typeof AdminQuangCaoRoute
  '/admin/tai-nguyen': typeof AdminTaiNguyenRoute
  '/news/da-luu': typeof NewsDaLuuRoute
  '/news/tim-kiem': typeof NewsTimKiemRoute
  '/portal/dang-ky': typeof PortalDangKyRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/bai-viet/$id': typeof AdminBaiVietIdRoute
  '/news/$topic/$category': typeof NewsTopicCategoryRoute
  '/news/article/$id': typeof NewsArticleIdRoute
  '/admin/bai-viet/': typeof AdminBaiVietIndexRoute
  '/news/$topic/': typeof NewsTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dang-nhap'
    | '/news'
    | '/portal'
    | '/admin/dang-ky'
    | '/admin/hoi-phi'
    | '/admin/hoi-vien'
    | '/admin/nguoi-dung'
    | '/admin/phan-bien'
    | '/admin/quang-cao'
    | '/admin/tai-nguyen'
    | '/news/da-luu'
    | '/news/tim-kiem'
    | '/portal/dang-ky'
    | '/admin/'
    | '/news/'
    | '/portal/'
    | '/admin/bai-viet/$id'
    | '/news/$topic/$category'
    | '/news/article/$id'
    | '/admin/bai-viet/'
    | '/news/$topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dang-nhap'
    | '/admin/dang-ky'
    | '/admin/hoi-phi'
    | '/admin/hoi-vien'
    | '/admin/nguoi-dung'
    | '/admin/phan-bien'
    | '/admin/quang-cao'
    | '/admin/tai-nguyen'
    | '/news/da-luu'
    | '/news/tim-kiem'
    | '/portal/dang-ky'
    | '/admin'
    | '/news'
    | '/portal'
    | '/admin/bai-viet/$id'
    | '/news/$topic/$category'
    | '/news/article/$id'
    | '/admin/bai-viet'
    | '/news/$topic'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dang-nhap'
    | '/news'
    | '/portal'
    | '/admin/dang-ky'
    | '/admin/hoi-phi'
    | '/admin/hoi-vien'
    | '/admin/nguoi-dung'
    | '/admin/phan-bien'
    | '/admin/quang-cao'
    | '/admin/tai-nguyen'
    | '/news/da-luu'
    | '/news/tim-kiem'
    | '/portal/dang-ky'
    | '/admin/'
    | '/news/'
    | '/portal/'
    | '/admin/bai-viet/$id'
    | '/news/$topic/$category'
    | '/news/article/$id'
    | '/admin/bai-viet/'
    | '/news/$topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DangNhapRoute: typeof DangNhapRoute
  NewsRoute: typeof NewsRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dang-ky': {
      id: '/admin/dang-ky'
      path: '/dang-ky'
      fullPath: '/admin/dang-ky'
      preLoaderRoute: typeof AdminDangKyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hoi-phi': {
      id: '/admin/hoi-phi'
      path: '/hoi-phi'
      fullPath: '/admin/hoi-phi'
      preLoaderRoute: typeof AdminHoiPhiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hoi-vien': {
      id: '/admin/hoi-vien'
      path: '/hoi-vien'
      fullPath: '/admin/hoi-vien'
      preLoaderRoute: typeof AdminHoiVienRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nguoi-dung': {
      id: '/admin/nguoi-dung'
      path: '/nguoi-dung'
      fullPath: '/admin/nguoi-dung'
      preLoaderRoute: typeof AdminNguoiDungRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/phan-bien': {
      id: '/admin/phan-bien'
      path: '/phan-bien'
      fullPath: '/admin/phan-bien'
      preLoaderRoute: typeof AdminPhanBienRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quang-cao': {
      id: '/admin/quang-cao'
      path: '/quang-cao'
      fullPath: '/admin/quang-cao'
      preLoaderRoute: typeof AdminQuangCaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tai-nguyen': {
      id: '/admin/tai-nguyen'
      path: '/tai-nguyen'
      fullPath: '/admin/tai-nguyen'
      preLoaderRoute: typeof AdminTaiNguyenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/da-luu': {
      id: '/news/da-luu'
      path: '/da-luu'
      fullPath: '/news/da-luu'
      preLoaderRoute: typeof NewsDaLuuRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/tim-kiem': {
      id: '/news/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/news/tim-kiem'
      preLoaderRoute: typeof NewsTimKiemRouteImport
      parentRoute: typeof NewsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dang-ky': {
      id: '/portal/dang-ky'
      path: '/dang-ky'
      fullPath: '/portal/dang-ky'
      preLoaderRoute: typeof PortalDangKyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/bai-viet/': {
      id: '/admin/bai-viet/'
      path: '/bai-viet'
      fullPath: '/admin/bai-viet/'
      preLoaderRoute: typeof AdminBaiVietIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bai-viet/$id': {
      id: '/admin/bai-viet/$id'
      path: '/bai-viet/$id'
      fullPath: '/admin/bai-viet/$id'
      preLoaderRoute: typeof AdminBaiVietIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/$topic/': {
      id: '/news/$topic/'
      path: '/$topic'
      fullPath: '/news/$topic/'
      preLoaderRoute: typeof NewsTopicIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$topic/$category': {
      id: '/news/$topic/$category'
      path: '/$topic/$category'
      fullPath: '/news/$topic/$category'
      preLoaderRoute: typeof NewsTopicCategoryRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/article/$id': {
      id: '/news/article/$id'
      path: '/article/$id'
      fullPath: '/news/article/$id'
      preLoaderRoute: typeof NewsArticleIdRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDangKyRoute: typeof AdminDangKyRoute
  AdminHoiPhiRoute: typeof AdminHoiPhiRoute
  AdminHoiVienRoute: typeof AdminHoiVienRoute
  AdminNguoiDungRoute: typeof AdminNguoiDungRoute
  AdminPhanBienRoute: typeof AdminPhanBienRoute
  AdminQuangCaoRoute: typeof AdminQuangCaoRoute
  AdminTaiNguyenRoute: typeof AdminTaiNguyenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBaiVietIdRoute: typeof AdminBaiVietIdRoute
  AdminBaiVietIndexRoute: typeof AdminBaiVietIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDangKyRoute: AdminDangKyRoute,
  AdminHoiPhiRoute: AdminHoiPhiRoute,
  AdminHoiVienRoute: AdminHoiVienRoute,
  AdminNguoiDungRoute: AdminNguoiDungRoute,
  AdminPhanBienRoute: AdminPhanBienRoute,
  AdminQuangCaoRoute: AdminQuangCaoRoute,
  AdminTaiNguyenRoute: AdminTaiNguyenRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBaiVietIdRoute: AdminBaiVietIdRoute,
  AdminBaiVietIndexRoute: AdminBaiVietIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NewsRouteChildren {
  NewsDaLuuRoute: typeof NewsDaLuuRoute
  NewsTimKiemRoute: typeof NewsTimKiemRoute
  NewsIndexRoute: typeof NewsIndexRoute
  NewsTopicCategoryRoute: typeof NewsTopicCategoryRoute
  NewsArticleIdRoute: typeof NewsArticleIdRoute
  NewsTopicIndexRoute: typeof NewsTopicIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsDaLuuRoute: NewsDaLuuRoute,
  NewsTimKiemRoute: NewsTimKiemRoute,
  NewsIndexRoute: NewsIndexRoute,
  NewsTopicCategoryRoute: NewsTopicCategoryRoute,
  NewsArticleIdRoute: NewsArticleIdRoute,
  NewsTopicIndexRoute: NewsTopicIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PortalRouteChildren {
  PortalDangKyRoute: typeof PortalDangKyRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDangKyRoute: PortalDangKyRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DangNhapRoute: DangNhapRoute,
  NewsRoute: NewsRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
